spring:
  application:
    name: backgomWineBack
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 10MB



  datasource:
    hikari:
      username: backgom
      password: backgom
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://backgom.iptime.org:43306/backgom
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
      minimum-idle: 5

  h2:
    console:
      enabled: true

jwt:
  issuer: BACKGOM
  secret_key: BACKGOM_SECRET_KEY

logging:
  config: classpath:config/logs/logback-spring.xml
  level:
    root: INFO ##
    org.springframework: INFO
    org.springframework.web: INFO
    org.springframework.boot.security: DEBUG
    org.hibernate.SQL: DEBUG
    com.zaxxer.hikari: INFO
    org.h2.server.web: DEBUG
    io.netty: INFO
    com.backgom: DEBUG
    org.springframework.session.data.redis: off

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/**/*.xml

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

#    context-path: /api

imagePath:
  clubMain: /Users/jeonghoyeon/backgomwine/club
  userPicture: /Users/jeonghoyeon/backgomwine/user
#  clubMain: /Users/backgom-air/backgomwine/club
#  userPicture: /Users/backgom-air/backgomwine/user

