200ok: ' 성 공 '
204ok: ' 성 공 '
202ok: ' 미정의성공 '
nodata: ' 조회되는 결과가 없습니다. '
notdefine: ' 정의되지않은 오류입니다 '
invalid: ' {0} 값은 무효입니다'
invaliduser: ' 세션이 만료됐거나 존재하지 않는 사용자 입니다. '
empty_key: ' {0} Key 가 존재하지 않습니다'
empty_value: ' {0} 값은 필수입니다'
too_long: ' {0} 값은 너무 깁니다 (최대 {1}자 까지)'
too_short: ' {0} 값은 너무 짧습니다 (최소 {1}자 이상)'
wrong_length: ' {0} 값은 길이가 틀렸습니다 ({1}자 필요)'
not_a_number: ' {0} 값은 숫자가 아닙니다'
white_space: ' {0} 값에 공백문자가 있습니다'
greater_than: ' {0} 값의 길이는 {1}이상을 요구합니다'
greater_than_or_equal_to: ' {0} 값은 {1}과 같거나 이상을 요구합니다'
less_than: ' {0} 값은 {1}과 같아야 합니다'
less_than_or_equal_to: ' {0} 값은 {1}과 같거나 이하를 요구합니다'
abnormal_format: ' {0} 값은 정상적인 포멧( {1} )이 아닙니다.'
accept: ' {0} 값은 허용되는 값이 아닙니다'
reject: ' {0} 값은 허용하지 않는 값 입니다.'
not_a_parameter: ' 전송된 파라미터 값이 없습니다'
not_a_httpheader: HTTP Header 중에서 {0} key 값이 존재하지않습니다
not_a_httpheadervalue: '{0} HTTP Header 값은  {1} 이어야 합니다'
too_long_httpheadervalue: ' {0} 값은 너무 깁니다 (최대 {1}자 까지)'
too_short_httpheadervalue: ' {0} 값은 너무 짧습니다 (최소 {1}자 이상)'
wrong_length_httpheadervalue: ' {0} 값은 길이가 틀렸습니다 ({1}자 필요)'
not_a_number_httpheadervalue: ' {0} 값은 숫자가 아닙니다'
white_space_httpheadervalue: ' {0} 값에 공백문자가 있습니다'
greater_than_httpheadervalue: ' {0} 값의 길이는 {1}이상을 요구합니다'
less_than_httpheadervalue: ' {0} 값은 {1}이하를 요구합니다'
abnormal_format_httpheadervalue: ' {0} 값은 정상적인 포멧( {1} )이 아닙니다.'
accept_httpheadervalue: ' {0} 값은 허용되는 값이 아닙니다'
reject_httpheadervalue: ' {0} 값은 허용하지 않는 값 입니다.'
empty_httpheadervalue: HTTP Header 중에서  {0} 의 value 값이 존재하지 않습니다
invalid_data: ' {0} 값이 잘못되었습니다'
invalid_xss: ' {0} 값이 잘못되었습니다 XSS'
special_char: ' {0} 값에 특수문자( {1} )가 입력되었습니다.'
ems_not_a_httpheader: HTTP Header 중에서 {0} key 값이 존재하지않습니다
ems_not_a_httpheadervalue: '{0} HTTP Header 값은  {1} 이어야 합니다'
ems_too_long_httpheadervalue: ' {0} 값은 너무 깁니다 (최대 {1}자 까지)'
ems_too_short_httpheadervalue: ' {0} 값은 너무 짧습니다 (최소 {1}자 이상)'
ems_wrong_length_httpheadervalue: ' {0} 값은 길이가 틀렸습니다 ({1}자 필요)'
ems_not_a_number_httpheadervalue: ' {0} 값은 숫자가 아닙니다'
ems_white_space_httpheadervalue: ' {0} 값에 공백문자가 있습니다'
ems_greater_than_httpheadervalue: ' {0} 값의 길이는 {1}이상을 요구합니다'
ems_less_than_httpheadervalue: ' {0} 값은 {1}이하를 요구합니다'
ems_abnormal_format_httpheadervalue: ' {0} 값은 정상적인 포멧( {1} )이 아닙니다.'
ems_accept_httpheadervalue: ' {0} 값은 허용되는 값이 아닙니다'
ems_reject_httpheadervalue: ' {0} 값은 허용하지 않는 값 입니다.'
ems_empty_httpheadervalue: HTTP Header 중에서  {0} 의 value 값이 존재하지 않습니다
ems_invalid_data: ' {0} 값이 잘못되었습니다'
ems_special_char: ' {0} 특수문자가 포함되어있습니다.'
ems_not_a_parameter: ' {0} 전송된 파라미터 값이 없습니다'
ems_empty_key: ' {0} Key 가 존재하지 않습니다'
ems_empty_value: ' {0} 값은 필수입니다'
database: ' 데이터 베이스 관련 이상이 감지되었습니다.'
config_file_not_found: '{0} 설정  {1} 파일이 없습니다. '
config_file_empty_key: '설정파일에 {0} Key 가 존재하지 않습니다 '
config_file_invalid_value: '설정파일에 {0} 값이 잘못되었습니다 '
java.io.FileNotFoundException: ' 파일을 찾을수 없습니다. '
java.io.IOException: ' 읽기 오류 입니다. '
java.sql.SQLException: ' 데이터 베이스 관련 이상이 감지되었습니다.'
org.springframework.dao.DataAccessException: null
org.apache.ibatis.javassist.NotFoundException: null
org.apache.http.conn.ConnectTimeoutException: null
java.net.SocketTimeoutException: null
java.net.ConnectException: null
org.springframework.jdbc.BadSqlGrammarException: ' 데이터베이스 오류({0})'
org.springframework.web.HttpMediaTypeNotSupportedException: HTTP Header 중에서 {0} 값이 누락되었습니다
java.lang.NullPointerException: Null Error
ava.lang.NumberFormatException: 숫자만 가능 합니다.
org.springframework.http.converter.HttpMessageNotReadableException: JSON 변환 중 문제가 있습니다.
com.fasterxml.jackson.core.io.JsonEOFException: JSON 변환 중 문제가 있습니다.
com.fasterxml.jackson.core.JsonParseException: JSON 변환 중 문제가 있습니다.
com.fasterxml.jackson.databind.JsonMappingException: JSON 변환 중 문제가 있습니다.
javax.script.ScriptException: 스크립트 실행 중 오류 입니다.
java.lang.NoSuchMethodException: ' 함수가 없습니다.'
com.fasterxml.jackson.databind.exc.MismatchedInputException: ' json 변환 오류.'
org.springframework.web.HttpRequestMethodNotSupportedException: '전문 규격을 확인 해 주세요.'
org.springframework.jdbc: ' 데이터베이스 오류 '
not_towken: 'not_towken'
org.springframework.data.redis.RedisConnectionFailureException: ' Redis 연결 실패 '
org.springframework.security.core.AuthenticationException: ' Authentication 실패 '
org.springframework.web.servlet.NoHandlerFoundException: ' 호출할수 없는 url입니다. '
fileSizeExceed: ' 파일 사이즈 제한 '
noUploadFile: ' 업로드 제한 '
fileUploadFail: '업로드 실패'
fileNotFound: '파일을 찾지 못하였습니다'
AccessDenied: 'Authentication 실패'
BindingException: 'Query 오류 ...'
not_token: '인증된 사용자가 아닙니다...'
login_fail: '아이디가 없거나 비밀번호가 틀렸습니다'
kepware_init_fail: 'kepware 초기화 실패'
influxdb_read_fail: 'influxDB 읽기 실패'
data_parsing_fail: '데이터 파싱 실패'
invalid_jwt_token: 'Expired or invalid JWT token'
check_userid_alreadyexist: ' 사용자 아이디가 이미 존재합니다. '
availableid: ' 사용 가능한 아이디입니다. '
disabledid: ' 사용이 불가능합니다. '
changepassword: ' 비밀번호 변경 필요 '
initpassword: ' 비밀번호 초기화 필요 '
ssologin: ' 통합인증을 통해 로그인해주십시오. '
fileTypeFail: ' 확인되지 않은 파일 확장자입니다. : {0}'
nopermission: ' 사용 권한이 없습니다. '
nomatchingip: ' 관리자 설정 IP로 로그인해주십시오. '
not_check_auth_number: ' 휴대폰 인증이 필요합니다. '
not_a_hptel: ' 휴대폰 정보가 없거나 사용자 정보가 없습니다. '
dev_conv_no_metakeyfield: 'Meta Map 의 키 필드가 정의 되지 않았습니다.[ {0} ]'
dev_conv_no_targetkeyfield: 'Target Map 의 키 필드가 정의 되지 않았습니다.[ {0} ]'
dev_conv_db_error: 'error : {0} , query : {1}'
sso_fail: ' SSO 서버 연결에 실패했습니다. '
sso_unavailable: ' SSO 서버 인증이 불가합니다. '
userid_decrypt_fail: ' 사용자아이디 복호화가 실패했습니다. '
available: ' 사용 가능합니다. '
disabled: ' 사용이 불가합니다. '
sso_api_call: 'hiway sso token API 호출 실패'
